### PR TITLE
Esp32-C3 - SVD 2024

### PR DESCRIPTION
**Pull request by kassane**
cc: @MasterQ32 

## References
- https://github.com/espressif/svd/commit/104da3c8e28a3c3a088c68a5ad1d31272b3d43ef
- https://github.com/esp-rs/esp-pacs/commit/55f9f6cdaff679a379b4f4f9f59b62b08deffdf2

### CODE REVIEW

**Comment by kassane** [comment]
CI error:
https://github.com/ZigEmbeddedGroup/microzig/actions/runs/8086188892/job/22095381000?pr=180#step:7:87

```bash
src/blinky.zig:63:14: error: no field named 'FUNC_OUT_SEL_CFG' in struct 'chip.types.peripherals.GPIO'
```

**Comment by MasterQ32** [comment]
> CI error: https://github.com/ZigEmbeddedGroup/microzig/actions/runs/8086188892/job/22095381000?pr=180#step:7:87
> 
> ```shell
> src/blinky.zig:63:14: error: no field named 'FUNC_OUT_SEL_CFG' in struct 'chip.types.peripherals.GPIO'
> ```

Looks like you should also fix the example then to compile with the new SVD file, seems like they changed the structure of the registers

**Comment by kassane** [comment]
Making the **GPIO** device regz auto-generated by build is very complicated. It changes with each version.
It might be useful to run tests between the files generated with a base interface to find out the effects.

It is not possible to do this PR at the moment. I will have to modify the espressif SVD or just add some extra code to microzig and refactor the example that is available.

**Comment by MasterQ32** [comment]
I mean you can just refactor the example, it's still just the hack i did a long time ago

**Pull request closed without merging**
