### PR TITLE
`ComptimeStringMap` replaced with `StaticStringMap`

### PR DESCRIPTION
**Pull request by tomasz-lisowski**
https://github.com/ziglang/zig/pull/19719 replaced `ComptimeStringMap` with `StaticStringMap`.

### CODE REVIEW

**Comment by tomasz-lisowski** [comment]
Perhaps this PR is a bit early. When will we move to 0.13.0?

**Comment by mattnite** [comment]
@tomasz-lisowski I'll be creating a `zig-master` branch early next week

**Comment by mochalins** [comment]
@mattnite Is the `zig-master` branch still on the table? Or would it be recommended to maintain a separate fork for master? If there is no objection to a `zig-master` branch but there is limited development time/effort, I'd love to open a PR with necessary updates.

**Comment by MatthiasPortzel** [comment]
My impression is that its just lack of time/effort. See also #198.

**Comment by vesim987** [comment]
Done in #198

**Pull request closed without merging**
