### PR TITLE
RP2040 Uart Refactor

### PR DESCRIPTION
**Pull request by haydenridd**
Should start looking pretty familiar to the other PRs!

The highlights:
- Removed configuration of GPIO pins by driver
- Added full transaction error handling
- Consolidated to new "uart.instance.[]" design pattern
- Added new "apply()" and "apply_runtime()" pattern for dual comptime/runtime error checking
- Added querying of current active UART errors
- Tweaked + renamed to write_blocking() and read_blocking() and added a timeout to match other APIs
- Tweaked syntax for using the UART as a logger + added ability to remove uart as logger

### CODE REVIEW

**Review by mattnite — APPROVED** [review]
Love these changes, thank you for all this hard work. Especially like apply vs apply_runtime.

**Comment by haydenridd** [comment]
> Very good work, but what i just asked: Can we even have any transmission error except Timeout during write operations? I mean we can't overrun, can't parity-error, can't break and all of that.
> 
> Apart from that, i'm fine

Yep indeed we can only get a timeout error from a write. Would you suggest separating out into `WriteError`/`ReadError`?

**Comment by ikskuh** [comment]
> Yep indeed we can only get a timeout error from a write. Would you suggest separating out into `WriteError`/`ReadError`?

Yeah, that's the idea. Maybe you could do `TransmitError` and `ReceiveError`?

**Comment by haydenridd** [comment]
> > Yep indeed we can only get a timeout error from a write. Would you suggest separating out into `WriteError`/`ReadError`?
> 
> Yeah, that's the idea. Maybe you could do `TransmitError` and `ReceiveError`?

For sure! I'll update then merge :)

**Pull request merged**
